# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := BLE_FINAL_ROBOTCAR_WHEELS_V5_FINAL_BUILD


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += BLE_API/source/BLE.o
OBJECTS += BLE_API/source/DiscoveredCharacteristic.o
OBJECTS += BLE_API/source/GapScanningParams.o
OBJECTS += BLE_API/source/services/DFUService.o
OBJECTS += BLE_API/source/services/UARTService.o
OBJECTS += BLE_API/source/services/URIBeaconConfigService.o
OBJECTS += HCSR04/HCSR04.o
OBJECTS += main.o
OBJECTS += nRF51822/source/btle/btle.o
OBJECTS += nRF51822/source/btle/btle_advertising.o
OBJECTS += nRF51822/source/btle/btle_discovery.o
OBJECTS += nRF51822/source/btle/btle_gap.o
OBJECTS += nRF51822/source/btle/btle_security.o
OBJECTS += nRF51822/source/btle/custom/custom_helper.o
OBJECTS += nRF51822/source/nRF5xDiscoveredCharacteristic.o
OBJECTS += nRF51822/source/nRF5xGap.o
OBJECTS += nRF51822/source/nRF5xGattClient.o
OBJECTS += nRF51822/source/nRF5xGattServer.o
OBJECTS += nRF51822/source/nRF5xSecurityManager.o
OBJECTS += nRF51822/source/nRF5xServiceDiscovery.o
OBJECTS += nRF51822/source/nRF5xn.o
OBJECTS += nRF51822/source/nordic-sdk/components/ble/ble_radio_notification/ble_radio_notification.o
OBJECTS += nRF51822/source/nordic-sdk/components/ble/ble_services/ble_dfu/ble_dfu.o
OBJECTS += nRF51822/source/nordic-sdk/components/ble/common/ble_advdata.o
OBJECTS += nRF51822/source/nordic-sdk/components/ble/common/ble_advdata_parser.o
OBJECTS += nRF51822/source/nordic-sdk/components/ble/common/ble_conn_params.o
OBJECTS += nRF51822/source/nordic-sdk/components/ble/common/ble_srv_common.o
OBJECTS += nRF51822/source/nordic-sdk/components/ble/device_manager/device_manager_peripheral.o
OBJECTS += nRF51822/source/nordic-sdk/components/drivers_nrf/ble_flash/ble_flash.o
OBJECTS += nRF51822/source/nordic-sdk/components/drivers_nrf/hal/nrf_delay.o
OBJECTS += nRF51822/source/nordic-sdk/components/drivers_nrf/hal/nrf_ecb.o
OBJECTS += nRF51822/source/nordic-sdk/components/drivers_nrf/hal/nrf_nvmc.o
OBJECTS += nRF51822/source/nordic-sdk/components/drivers_nrf/pstorage/pstorage.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/bootloader_dfu/bootloader_util_arm.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/bootloader_dfu/dfu_init_template.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/bootloader_dfu/experimental/dfu_app_handler.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/crc16/crc16.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/hci/hci_mem_pool.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/scheduler/app_scheduler.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/util/app_error.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/util/app_util_platform.o
OBJECTS += nRF51822/source/nordic-sdk/components/libraries/util/nrf_assert.o
OBJECTS += nRF51822/source/nordic-sdk/components/softdevice/common/softdevice_handler/softdevice_handler.o
OBJECTS += nRF51822/source/nordic-sdk/components/softdevice/common/softdevice_handler/softdevice_handler_appsh.o

 SYS_OBJECTS += mbed/TARGET_NRF51_DK/TOOLCHAIN_GCC_ARM/board.o
 SYS_OBJECTS += mbed/TARGET_NRF51_DK/TOOLCHAIN_GCC_ARM/cmsis_nvic.o
 SYS_OBJECTS += mbed/TARGET_NRF51_DK/TOOLCHAIN_GCC_ARM/retarget.o
 SYS_OBJECTS += mbed/TARGET_NRF51_DK/TOOLCHAIN_GCC_ARM/startup_NRF51822.o
 SYS_OBJECTS += mbed/TARGET_NRF51_DK/TOOLCHAIN_GCC_ARM/system_nrf51.o

INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../BLE_API
INCLUDE_PATHS += -I../BLE_API/ble
INCLUDE_PATHS += -I../BLE_API/ble/services
INCLUDE_PATHS += -I../BLE_API/source
INCLUDE_PATHS += -I../BLE_API/source/services
INCLUDE_PATHS += -I../HCSR04
INCLUDE_PATHS += -I../mbed/.
INCLUDE_PATHS += -I../mbed/TARGET_NRF51_DK
INCLUDE_PATHS += -I../mbed/TARGET_NRF51_DK/TARGET_NORDIC
INCLUDE_PATHS += -I../mbed/TARGET_NRF51_DK/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I../nRF51822
INCLUDE_PATHS += -I../nRF51822/bootloader
INCLUDE_PATHS += -I../nRF51822/source
INCLUDE_PATHS += -I../nRF51822/source/btle
INCLUDE_PATHS += -I../nRF51822/source/btle/custom
INCLUDE_PATHS += -I../nRF51822/source/common
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/ble
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/ble/ble_radio_notification
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/ble/ble_services
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/ble/ble_services/ble_dfu
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/ble/common
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/ble/device_manager
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/ble/device_manager/config
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/drivers_nrf
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/drivers_nrf/ble_flash
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/drivers_nrf/hal
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/drivers_nrf/pstorage
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/drivers_nrf/pstorage/config
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/libraries
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/libraries/bootloader_dfu
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/libraries/bootloader_dfu/experimental
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/libraries/bootloader_dfu/hci_transport
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/libraries/crc16
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/libraries/hci
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/libraries/scheduler
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/libraries/util
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/softdevice
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/softdevice/common
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/softdevice/common/softdevice_handler
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/softdevice/s130
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/softdevice/s130/doc
INCLUDE_PATHS += -I../nRF51822/source/nordic-sdk/components/softdevice/s130/include

LIBRARY_PATHS := -L../mbed/TARGET_NRF51_DK/TOOLCHAIN_GCC_ARM 
LIBRARIES := -l:libmbed.a 
LINKER_SCRIPT ?= ../mbed/TARGET_NRF51_DK/TOOLCHAIN_GCC_ARM/NRF51822.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = 'arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-mcpu=cortex-m0' '-mthumb'
CC      = 'arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-mcpu=cortex-m0' '-mthumb'
CPP     = 'arm-none-eabi-g++' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-mcpu=cortex-m0' '-mthumb'
LD      = 'arm-none-eabi-gcc'
ELF2BIN = 'arm-none-eabi-objcopy'
PREPROC = 'arm-none-eabi-cpp' '-E' '-P' '-Wl,--gc-sections' '-Wl,--wrap,main' '-mcpu=cortex-m0' '-mthumb'

SREC_CAT = srec_cat

C_FLAGS += -std=gnu99
C_FLAGS += -DDEVICE_ERROR_PATTERN=1
C_FLAGS += -DNRF51
C_FLAGS += -D__MBED__=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DTARGET_NRF51822
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_LOWPOWERTIMER=1
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTARGET_MCU_NRF51822_UNIFIED
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DTARGET_SDK11
C_FLAGS += -DARM_MATH_CM0
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DTARGET_NRF5
C_FLAGS += -DFEATURE_BLE=1
C_FLAGS += -DTARGET_M0
C_FLAGS += -DTARGET_MCU_NRF51
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL
C_FLAGS += -DTARGET_MCU_NRF51_UNIFIED
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -D__CORTEX_M0
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DTARGET_NORDIC
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DBLE_STACK_SUPPORT_REQD
C_FLAGS += -DTARGET_MCU_NRF51_32K_UNIFIED
C_FLAGS += -DTARGET_NRF51_DK
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DTARGET_MCU_NRF51822
C_FLAGS += -DTARGET_MCU_NORDIC_32K
C_FLAGS += -DSOFTDEVICE_PRESENT
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DS130
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1503074822.97
C_FLAGS += -DTARGET_LIKE_CORTEX_M0
C_FLAGS += -DTARGET_MCU_NRF51_32K
C_FLAGS += -include
C_FLAGS += mbed_config.h

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -DDEVICE_ERROR_PATTERN=1
CXX_FLAGS += -DNRF51
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DTARGET_NRF51822
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_LOWPOWERTIMER=1
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTARGET_MCU_NRF51822_UNIFIED
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DTARGET_SDK11
CXX_FLAGS += -DARM_MATH_CM0
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DTARGET_NRF5
CXX_FLAGS += -DFEATURE_BLE=1
CXX_FLAGS += -DTARGET_M0
CXX_FLAGS += -DTARGET_MCU_NRF51
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL
CXX_FLAGS += -DTARGET_MCU_NRF51_UNIFIED
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -D__CORTEX_M0
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DTARGET_NORDIC
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DBLE_STACK_SUPPORT_REQD
CXX_FLAGS += -DTARGET_MCU_NRF51_32K_UNIFIED
CXX_FLAGS += -DTARGET_NRF51_DK
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DTARGET_MCU_NRF51822
CXX_FLAGS += -DTARGET_MCU_NORDIC_32K
CXX_FLAGS += -DSOFTDEVICE_PRESENT
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DS130
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1503074822.97
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M0
CXX_FLAGS += -DTARGET_MCU_NRF51_32K
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -D__CORTEX_M0
ASM_FLAGS += -DTARGET_MCU_NRF51_32K
ASM_FLAGS += -DTARGET_MCU_NRF51822
ASM_FLAGS += -DTARGET_MCU_NORDIC_32K
ASM_FLAGS += -DSOFTDEVICE_PRESENT
ASM_FLAGS += -DNRF51
ASM_FLAGS += -DBLE_STACK_SUPPORT_REQD
ASM_FLAGS += -DTARGET_NRF51822
ASM_FLAGS += -DARM_MATH_CM0
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -DS130


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -mcpu=cortex-m0 -mthumb 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size

all: $(PROJECT).bin $(PROJECT)-combined.hex size


.asm.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter %.ld, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@


$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


$(PROJECT)-combined.hex: $(PROJECT).hex
	+@echo "NOTE: the $(SREC_CAT) binary is required to be present in your PATH. Please see http://srecord.sourceforge.net/ for more information."
	$(SREC_CAT) ../nRF51822/bootloader/s110_nrf51822_8.0.0_bootloader.hex ../nRF51822/bootloader/s130_nrf51_1.0.0_bootloader.hex  -intel $(PROJECT).hex -intel -o $(PROJECT)-combined.hex -intel --line-length=44
	+@echo "===== hex file ready to flash: $(OBJDIR)/$@ ====="

# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
